### PR TITLE
Update intelephense to 1.8.x

### PR DESCRIPTION
**Pull request by radmen**
Bumped version of intelephense to 1.8.

:point_right: [List of changes](https://github.com/bmewburn/vscode-intelephense/compare/v1.7.1...v1.8.0)

### CODE REVIEW

**Comment by radmen** [comment]
@marlonfan Intelephense bumped the default php version to 8.1.0. Should I do the same for this PR? I'm not sure if that change could introduce any BC issues.

**Comment by dvlpr91** [comment]
This should raise the intelephense version to 1.8.

An error message appears in the syntax where there is no problem, such as enum.

**Comment by dvlpr91** [comment]
@marlonfan Please review.

**Comment by marlonfan** [comment]
LGTM, Thank for this pr.

**Pull request merged**
