### PR TITLE
Always index when new dependency installed via composer

### PR DESCRIPTION
**Pull request by mihaelartz**
@marlonfan You must be implement system for watching all php files and give option to user for exclude some directories, files, this is hardcoded implementation, watch only root project, from subdirectories watching only vendor!

https://github.com/marlonfan/coc-phpls/commit/3f8327ac9a990a9c431a61aef626fa8b5afb7cc2#diff-f41e9d04a45c83f3b6f6e630f10117feL78
https://github.com/marlonfan/coc-phpls/commit/3f8327ac9a990a9c431a61aef626fa8b5afb7cc2#diff-f41e9d04a45c83f3b6f6e630f10117feL159

### CODE REVIEW

**Comment by marlonfan** [comment]
I don't see any implementation of [vscode-intelephense](https://github.com/bmewburn/vscode-intelephense), In addition, I have not yet understood the specific implementation of [intelephense](https://github.com/bmewburn/intelephense-docs).

eg. how to submit client configuration to server...?

**Comment by mihaelartz** [comment]
@marlonfan For vscode this implementation is unnecessary

https://github.com/bmewburn/vscode-intelephense/blob/master/package.json#L86
https://github.com/bmewburn/vscode-intelephense/blob/master/package.json#L95

**Comment by mihaelartz** [comment]
@marlonfan For VSCode this implementation is unnecessary.

**Comment by marlonfan** [comment]
Nice, i get it.

thanks for you job.

**Comment by marlonfan** [comment]
@mihaelartz Wow. Are you considering cooperating to advance this project?

**Comment by mihaelartz** [comment]
@marlonfan Why not :)

**Pull request merged**
