### PR TITLE
Upgrade intelephense to 1.9

### PR DESCRIPTION
**Pull request by lewissteele**
This bumps intelephense up to 1.9 which adds support for PHP 8.1 features like enums:

Peek 2023-04-01 12-33

I've installed onto my local nvim and it works great! :smile:

### CODE REVIEW

**Comment by z0w13** [comment]
You've added a `.yarnrc.yml` specifying `yarnPath` without also committing the yarn version you're referencing to, is yarn 1.0 required or was this on accident:

```yaml
yarnPath: .yarn/releases/yarn-1.22.19.cjs
```

this will error when people don't manually grab that yarn release and put it into that folder

**Comment by marlonfan** [comment]
@z0w13 You are right, I deleted this file when publishing, I will update the code later

**Comment by marlonfan** [comment]
@z0w13 master's code has been updated to fix this issue

**Comment by lewissteele** [comment]
Sorry about that, I don't have much experience with yarn, I'm more of an npm man :laughing: 

@marlonfan Thanks for fixing it

**Pull request merged**
